# Use an official OpenJDK image as the base image
FROM openjdk:17-jdk-slim

# Set environment variables
ENV SPRING_PROFILES_ACTIVE=prod

# Set the working directory in the container
WORKDIR /app

# Copy the application JAR file to the container
COPY target/01-miniProject-Counsellors-Portal.jar app.jar

# Expose the port on which the application will run
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]