# Use an official OpenJDK image as the base image
FROM openjdk:17-jdk-slim

ENV SPRING_PROFILES_ACTIVE=prod

WORKDIR /app

COPY target/01-miniProject-Counsellors-Portal.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/app.jar"]